import os

#####
# Environment Variables
#####
DEPLOYMENT_MODE = os.getenv("DEPLOYMENT_MODE", "local")

if (DEPLOYMENT_MODE == "production"):
    S3_UPLOADS_BUCKET=os.getenv("COA_FORMS_PROD_S3_UPLOADS_BUCKET")
    DYNAMO_DB_TABLE="coa-forms-prod"
    EMAIL_ADDRESS_OPO=os.getenv("COA_FORMS_PROD_EMAIL_ADDRESS_OPO")
    EMAIL_ADDRESS_APD=os.getenv("COA_FORMS_PROD_EMAIL_ADDRESS_APD")
    EMAIL_ADDRESS_REPLYTO=os.getenv("COA_FORMS_PROD_EMAIL_ADDRESS_REPLYTO")
    EMAIL_ADDRESS_SMOKE_TEST=os.getenv("COA_FORMS_PROD_EMAIL_ADDRESS_SMOKE_TEST")
elif (DEPLOYMENT_MODE == "staging"):
    DYNAMO_DB_TABLE="coa-forms-dev"
    S3_UPLOADS_BUCKET=os.getenv("COA_FORMS_STAGING_S3_UPLOADS_BUCKET")
    EMAIL_ADDRESS_OPO=os.getenv("COA_FORMS_STAGING_EMAIL_ADDRESS_OPO")
    EMAIL_ADDRESS_APD=os.getenv("COA_FORMS_STAGING_EMAIL_ADDRESS_APD")
    EMAIL_ADDRESS_REPLYTO=os.getenv("COA_FORMS_STAGING_EMAIL_ADDRESS_REPLYTO")
    EMAIL_ADDRESS_SMOKE_TEST=os.getenv("COA_FORMS_STAGING_EMAIL_ADDRESS_SMOKE_TEST")
elif (DEPLOYMENT_MODE == "dev"):
    DYNAMO_DB_TABLE="coa-forms-dev"
    S3_UPLOADS_BUCKET="coa-forms-uploads-pr"
    EMAIL_ADDRESS_OPO=os.getenv("COA_FORMS_STAGING_EMAIL_ADDRESS_OPO")
    EMAIL_ADDRESS_APD=os.getenv("COA_FORMS_STAGING_EMAIL_ADDRESS_APD")
    EMAIL_ADDRESS_REPLYTO=os.getenv("COA_FORMS_STAGING_EMAIL_ADDRESS_REPLYTO")
    EMAIL_ADDRESS_SMOKE_TEST=os.getenv("COA_FORMS_STAGING_EMAIL_ADDRESS_SMOKE_TEST")
elif (DEPLOYMENT_MODE == "local"):
    DYNAMO_DB_TABLE=os.getenv("COA_FORMS_LOCAL_DYNAMO_DB_TABLE")
    S3_UPLOADS_BUCKET=os.getenv("COA_FORMS_LOCAL_S3_UPLOADS_BUCKET")
    EMAIL_ADDRESS_OPO=os.getenv("COA_FORMS_LOCAL_EMAIL_ADDRESS_OPO")
    EMAIL_ADDRESS_APD=os.getenv("COA_FORMS_LOCAL_EMAIL_ADDRESS_APD")
    EMAIL_ADDRESS_REPLYTO=os.getenv("COA_FORMS_LOCAL_EMAIL_ADDRESS_REPLYTO")
    EMAIL_ADDRESS_SMOKE_TEST=os.getenv("COA_FORMS_LOCAL_EMAIL_ADDRESS_SMOKE_TEST")

S3_KEY                    = os.getenv("AWS_ACCESS_KEY_ID")
S3_SECRET                 = os.getenv("AWS_SECRET_ACCESS_KEY")
DEFALUT_REGION            = os.getenv("AWS_DEFAULT_REGION", "us-east-1")
S3_LOCATION               = f'http://{S3_UPLOADS_BUCKET}.s3.amazonaws.com/'
